import type { DirectionEffectAsset, DirectionPresetAsset } from "./types";

export const directionEffectAssets: DirectionEffectAsset[] = [
  {
    id: "spark_ambient_blue",
    type: "particle",
    kind: "ambient_spark",
    label: "青い光粒子",
    tags: ["ambient", "deep-dive", "technology"],
    compatibleIntents: ["deep_dive", "emphasis", "summary"],
    compatibleCharacters: ["rei", "mikoto"],
    intensity: "medium",
    durationMs: 7000,
    cooldownMs: 1000,
    color: "#64d8ff",
    count: 46,
    size: [0.025, 0.06],
    spread: [5.2, 2.4, 2.4],
    velocity: [0.01, 0.028, 0]
  },
  {
    id: "bubble_question_float",
    type: "particle",
    kind: "bubble_float",
    label: "疑問の泡",
    tags: ["question", "soft", "float"],
    compatibleIntents: ["question", "doubt"],
    compatibleCharacters: ["mikoto", "rei"],
    intensity: "medium",
    durationMs: 6500,
    cooldownMs: 1200,
    color: "#b7ecff",
    count: 30,
    size: [0.055, 0.15],
    spread: [4.8, 2.2, 2.2],
    velocity: [0.006, 0.02, 0]
  },
  {
    id: "petal_soft_fall",
    type: "particle",
    kind: "petal_fall",
    label: "柔らかく舞う花弁",
    tags: ["petal", "celebration", "transition", "soft"],
    compatibleIntents: ["celebration", "transition", "summary"],
    compatibleCharacters: ["rei", "mikoto"],
    intensity: "low",
    durationMs: 8500,
    cooldownMs: 1600,
    color: "#ffd6e7",
    count: 72,
    size: [0.07, 0.16],
    spread: [6.2, 3.4, 2.8],
    velocity: [0.018, -0.05, 0.006]
  },
  {
    id: "focus_emphasis_pulse",
    type: "particle",
    kind: "focus_pulse",
    label: "強調の集中光",
    tags: ["emphasis", "focus", "pulse"],
    compatibleIntents: ["emphasis", "supplement"],
    compatibleCharacters: ["rei"],
    intensity: "high",
    durationMs: 4800,
    cooldownMs: 1200,
    color: "#fff15f",
    count: 36,
    size: [0.035, 0.08],
    spread: [3.4, 1.6, 1.7],
    velocity: [0, 0.018, 0]
  },
  {
    id: "warning_red_flash",
    type: "particle",
    kind: "warning_flash",
    label: "警告の赤い瞬き",
    tags: ["warning", "sharp", "attention"],
    compatibleIntents: ["warning", "tsukkomi"],
    compatibleCharacters: ["mikoto", "rei"],
    intensity: "high",
    durationMs: 4200,
    cooldownMs: 1400,
    color: "#ff6b4a",
    count: 28,
    size: [0.04, 0.1],
    spread: [4.2, 1.8, 2],
    velocity: [0.018, 0.016, 0]
  }
];

export const directionPresets: DirectionPresetAsset[] = [
  {
    id: "emphasis_basic",
    type: "direction_preset",
    intent: "emphasis",
    label: "基本の強調",
    tags: ["emphasis", "focus"],
    compatibleIntents: ["emphasis", "supplement"],
    compatibleCharacters: ["rei"],
    intensity: "medium",
    durationMs: 5200,
    motion: "point",
    camera: "close",
    scenePreset: "demo",
    effects: ["focus_emphasis_pulse"]
  },
  {
    id: "question_light",
    type: "direction_preset",
    intent: "question",
    label: "軽い疑問",
    tags: ["question", "soft"],
    compatibleIntents: ["question", "doubt"],
    compatibleCharacters: ["mikoto", "rei"],
    intensity: "medium",
    durationMs: 6500,
    motion: "think",
    camera: "side",
    scenePreset: "question",
    effects: ["bubble_question_float"]
  },
  {
    id: "warning_focus",
    type: "direction_preset",
    intent: "warning",
    label: "注意喚起",
    tags: ["warning", "attention"],
    compatibleIntents: ["warning", "tsukkomi"],
    compatibleCharacters: ["mikoto", "rei"],
    intensity: "high",
    conflicts: ["focus_emphasis_pulse"],
    durationMs: 4200,
    motion: "point",
    camera: "side",
    scenePreset: "warning",
    effects: ["warning_red_flash"]
  },
  {
    id: "summary_wide",
    type: "direction_preset",
    intent: "summary",
    label: "まとめの広角",
    tags: ["summary", "wide", "calm"],
    compatibleIntents: ["summary"],
    compatibleCharacters: ["rei", "mikoto"],
    intensity: "medium",
    durationMs: 7200,
    motion: "present",
    camera: "wide",
    scenePreset: "summary",
    effects: ["spark_ambient_blue", "petal_soft_fall"]
  },
  {
    id: "celebration_petal",
    type: "direction_preset",
    intent: "celebration",
    label: "祝祭の花弁",
    tags: ["celebration", "petal"],
    compatibleIntents: ["celebration", "transition"],
    compatibleCharacters: ["rei", "mikoto"],
    intensity: "medium",
    durationMs: 8500,
    motion: "wave",
    camera: "wide",
    scenePreset: "question",
    effects: ["petal_soft_fall"]
  }
];
